{
  "modified": "2023-12-25T20:50:36Z",
  "published": "2023-12-25T20:50:36Z",
  "schema_version": "1.5.0",
  "id": "MAL-2023-8768",
  "summary": "Malicious code in newpackagetest2028 (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n\n## Source: khulnasoft-package-analysis (4e92d513cfce2f0d7957442fa2ebddb1118f04dd175a20a1a9344cb4e4fbc906)\nThe OpenSSF Package Analysis project identified 'newpackagetest2028' @ 1.0.0 (pypi) as malicious.\n\nIt is considered malicious because:\n\n- The package communicates with a domain associated with malicious activity.\n\n- The package executes one or more commands associated with malicious behavior.\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "newpackagetest2028"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "credits": [
    {
      "name": "OpenSSF: Package Analysis",
      "type": "FINDER",
      "contact": [
        "https://github.com/khulnasoft-lab/package-analysis",
        "https://openssf.slack.com/channels/package_analysis"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "import_time": "2023-12-29T10:34:32.739011859Z",
        "modified_time": "2023-12-25T20:50:36Z",
        "sha256": "4e92d513cfce2f0d7957442fa2ebddb1118f04dd175a20a1a9344cb4e4fbc906",
        "source": "khulnasoft-package-analysis",
        "versions": [
          "1.0.0"
        ]
      }
    ]
  }
}
