{
  "modified": "2024-06-25T13:35:13Z",
  "published": "2024-06-25T13:35:13Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5116",
  "aliases": [
    "SNYK-PYTHON-ETHERAPI-5292131"
  ],
  "summary": "Malicious code in etherapi (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "etherapi",
        "purl": "pkg:pypi/etherapi"
      },
      "versions": [
        "1.0"
      ]
    }
  ],
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/DataDog/malicious-software-packages-dataset"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-ETHERAPI-5292131"
    },
    {
      "type": "ARTICLE",
      "url": "https://www.fortinet.com/blog/threat-research/supply-chain-attack-via-new-malicious-python-packages"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-03896",
        "import_time": "2024-06-28T02:48:55.974443649Z",
        "modified_time": "2024-06-25T13:35:13Z",
        "sha256": "63466665c587219c62cad6ba48e41e8149fbe599c9f6380f1ce3b01bd0f72bc1",
        "source": "reversing-labs",
        "versions": [
          "1.0"
        ]
      }
    ]
  }
}
