{
  "modified": "2024-06-25T13:41:50Z",
  "published": "2024-06-25T13:41:50Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5916",
  "aliases": [
    "SNYK-PYTHON-REQUEWSTS-6513392"
  ],
  "summary": "Malicious code in requewsts (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "requewsts",
        "purl": "pkg:pypi/requewsts"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-REQUEWSTS-6513392"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-04717",
        "import_time": "2024-06-28T02:50:33.579789723Z",
        "modified_time": "2024-06-25T13:41:50Z",
        "sha256": "26012216f52e174e96ce3b72069028ef698e68c80c6cb9a50b655926e0af3dd7",
        "source": "reversing-labs",
        "versions": [
          "1.0.0"
        ]
      }
    ]
  }
}
