{
  "modified": "2024-06-25T13:39:02Z",
  "published": "2024-06-25T13:39:02Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5588",
  "aliases": [
    "SNYK-PYTHON-PYCOAD-6513679"
  ],
  "summary": "Malicious code in py-coad (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "py-coad",
        "purl": "pkg:pypi/py-coad"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-PYCOAD-6513679"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-04370",
        "import_time": "2024-06-28T02:49:52.317743866Z",
        "modified_time": "2024-06-25T13:39:02Z",
        "sha256": "107a2507949b10f31682ab5412d7474099f42d79fa1f8264925dbbfd7edcca1a",
        "source": "reversing-labs",
        "versions": [
          "1.0.0"
        ]
      }
    ]
  }
}
