{
  "modified": "2024-06-25T13:39:54Z",
  "published": "2024-06-25T13:39:54Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5695",
  "summary": "Malicious code in pydefenderultra (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pydefenderultra",
        "purl": "pkg:pypi/pydefenderultra"
      },
      "versions": [
        "1.0.1",
        "1.0.0"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-04478",
        "import_time": "2024-06-28T02:50:04.966009772Z",
        "modified_time": "2024-06-25T13:39:54Z",
        "sha256": "d1593908257855f8c0225b7e0fbb3f6f728351f0be45c6b1660b3e912b1a9199",
        "source": "reversing-labs",
        "versions": [
          "1.0.1",
          "1.0.0"
        ]
      }
    ]
  }
}
