{
  "modified": "2024-06-25T13:38:43Z",
  "published": "2024-06-25T13:38:43Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5550",
  "aliases": [
    "SNYK-PYTHON-PJLLOW-6513685"
  ],
  "summary": "Malicious code in pjllow (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pjllow",
        "purl": "pkg:pypi/pjllow"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-PJLLOW-6513685"
    },
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-04332",
        "import_time": "2024-06-28T02:49:47.893815393Z",
        "modified_time": "2024-06-25T13:38:43Z",
        "sha256": "bd4d01961ee4712873f645a7a1ebd6aef8a523679022f30465a317a8e4927520",
        "source": "reversing-labs",
        "versions": [
          "1.0.0"
        ]
      }
    ]
  }
}
