{
  "modified": "2024-06-25T13:33:28Z",
  "published": "2024-06-25T13:33:28Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-4899",
  "summary": "Malicious code in cloud-credentials (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "cloud-credentials",
        "purl": "pkg:pypi/cloud-credentials"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-03679",
        "import_time": "2024-06-28T02:48:30.821241245Z",
        "modified_time": "2024-06-25T13:33:28Z",
        "sha256": "bb41a80f7c71632a5ed2f0f9003b7b39f71d9daab525201b8232144b88695aab",
        "source": "reversing-labs",
        "versions": [
          "1.0.0"
        ]
      }
    ]
  }
}
