{
  "modified": "2024-06-25T13:33:27Z",
  "published": "2024-06-25T13:33:27Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-4898",
  "aliases": [
    "SNYK-PYTHON-CLOROMA-6513703"
  ],
  "summary": "Malicious code in cloroma (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "cloroma",
        "purl": "pkg:pypi/cloroma"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-CLOROMA-6513703"
    },
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-03678",
        "import_time": "2024-06-28T02:48:30.719097443Z",
        "modified_time": "2024-06-25T13:33:27Z",
        "sha256": "51411dff081bda8272574c842cc57b93cf246b6856c2af1399fd8596171c9c18",
        "source": "reversing-labs",
        "versions": [
          "1.0.0"
        ]
      }
    ]
  }
}
