{
  "modified": "2024-06-25T13:41:48Z",
  "published": "2024-06-25T13:41:48Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5913",
  "aliases": [
    "SNYK-PYTHON-REQUETSA-6513520"
  ],
  "summary": "Malicious code in requetsa (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "requetsa",
        "purl": "pkg:pypi/requetsa"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-REQUETSA-6513520"
    },
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-04714",
        "import_time": "2024-06-28T02:50:33.159783316Z",
        "modified_time": "2024-06-25T13:41:48Z",
        "sha256": "a5ec07eb55b0bc9eacc117c9c2fae16236663001a06cbbc1267a3df04cdb1061",
        "source": "reversing-labs",
        "versions": [
          "1.0.0"
        ]
      }
    ]
  }
}
