{
  "modified": "2024-06-25T13:33:04Z",
  "published": "2024-06-25T13:33:04Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-4850",
  "aliases": [
    "SNYK-PYTHON-CAPMONSTERCLOUCLIENT-6513718"
  ],
  "summary": "Malicious code in capmonsterclouclient (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "capmonsterclouclient",
        "purl": "pkg:pypi/capmonsterclouclient"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-CAPMONSTERCLOUCLIENT-6513718"
    },
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-03630",
        "import_time": "2024-06-28T02:48:25.438354816Z",
        "modified_time": "2024-06-25T13:33:04Z",
        "sha256": "51f8e9a5fab44586628d554317f9d1d04428d6cc4c71bbb4f0d5e580cfef1420",
        "source": "reversing-labs",
        "versions": [
          "1.0.0"
        ]
      }
    ]
  }
}
